import useSWR from "swr";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const fetcher = (query) =>
  fetch("/api/graphql", {
    method: "POST",
    headers: {
      "Content-type": "application/json",
    },
    body: JSON.stringify({ query }),
  })
    .then((res) => res.json())
    .then((json) => json.data);

export default function Index() {
  const { data, error } = useSWR("{ users { name } }", fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  const { users } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://nextjs.org">Next.js on Azure with API Routes!</a>
        </h1>

        <p className={styles.description}>
          The following grid is back from the server.
        </p>

        <div className={styles.grid}>
          {users.map((user, i) => (
            <a href="#" key={i} className={styles.card}>
              <h2>{user.name}</h2>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://docs.microsoft.com/azure/static-web-apps/deploy-nextjs-hybrid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built with Next.js, hosted on Azure.
        </a>
      </footer>
    </div>
  );
}
